#!/usr/bin/env python3
"""
Author: Michal Szymanski <misiektoja-github@rm-rf.ninja>
v1.0

LoL Match History Comparison Tool

This script compares two League of Legends match history CSV files generated by lol_monitor and determines
whether they likely belong to the same player. It analyzes multiple features including:

- Champion pool similarity (frequency distribution)
- KDA profile (mean and standard deviation)
- Win rate similarity
- Average match duration
- Time-of-day playing patterns
- Teammate overlap (summoner names)
- Role and lane preferences
- Average champion level
- Game mode preferences
- Temporal overlap detection (checks if matches occurred at the same time)

The script computes similarity scores for each feature and combines them into an overall score (0-100) with a verdict
indicating the likelihood that both CSV files represent the same player. It can output results in either human-readable
format or JSON for programmatic use.

Usage:
    python lol_compare_csvs.py file1.csv file2.csv [--limit N] [--json] [--pretty] [--no-overlap-check]

Python pip3 requirements:

pandas
"""

import argparse
import json
import math
import os
import re
from collections import Counter
from datetime import datetime
from typing import Dict, List, Tuple, Optional

import pandas as pd


# Loads and normalizes a LoL matches CSV into a clean DataFrame
def load_matches(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, engine="c")  # default quotechar='"' handles your sample

    # Normalize column names aggressively
    def norm(s: str) -> str:
        s = str(s)
        s = s.replace("\ufeff", "")  # strip BOM if present
        s = s.strip().strip('"').strip("'")
        s = re.sub(r"\s+", " ", s)
        s = s.lower()
        return s

    original_cols = list(df.columns)
    ncols = [norm(c) for c in df.columns]
    df.columns = ncols

    # Map many possible header variants to canonical names
    def find_col(aliases: List[str]) -> Optional[str]:
        for a in aliases:
            if a in df.columns:
                return a
        return None

    colmap = {}

    # Define alias sets
    colmap_candidates = {
        "start": ["match start", "start", "game start", "start time", "start_datetime"],
        "stop": ["match stop", "stop", "game stop", "end", "match end", "game end", "stop time"],
        "duration": ["duration", "match duration", "game duration", "game length", "length"],
        "victory": ["victory", "win", "result", "won", "outcome"],
        "kills": ["kills", "k"],
        "deaths": ["deaths", "d"],
        "assists": ["assists", "a"],
        "champion": ["champion", "champ", "character", "hero"],
        "level": ["level", "champ level", "champion level", "lvl"],
        "role": ["role", "position", "primary role"],
        "lane": ["lane", "position lane", "primary lane"],
        "game_mode": ["game mode", "gamemode", "mode", "game type", "match type"],
        "blue": ["blue team", "blue", "team blue", "allies", "ally team", "teammates", "team 1"],
        "red": ["red team", "red", "team red", "enemies", "enemy team", "opponents", "team 2"],
    }

    for canon, aliases in colmap_candidates.items():
        found = find_col(aliases)
        if found is not None:
            colmap[found] = canon

    # Rename found columns to canonical names
    if colmap:
        df = df.rename(columns=colmap)

    # Create any missing expected columns with safe defaults
    for needed in [
        "start",
        "stop",
        "duration",
        "victory",
        "kills",
        "deaths",
        "assists",
        "champion",
        "level",
        "role",
        "lane",
        "game_mode",
        "blue",
        "red",
    ]:
        if needed not in df.columns:
            if needed in ("blue", "red"):
                df[needed] = ""
            else:
                df[needed] = pd.NA

    # Parse datetimes; treat naive as UTC
    df["start"] = pd.to_datetime(df["start"], errors="coerce", utc=True)
    df["stop"] = pd.to_datetime(df["stop"], errors="coerce", utc=True)

    # Duration to minutes
    df["duration_min"] = df["duration"].apply(parse_duration_to_minutes)

    # Victory normalization to 1/0
    df["victory"] = df["victory"].apply(normalize_victory)

    # Numeric K/D/A
    df["kills"] = pd.to_numeric(df["kills"], errors="coerce")
    df["deaths"] = pd.to_numeric(df["deaths"], errors="coerce")
    df["assists"] = pd.to_numeric(df["assists"], errors="coerce")

    # KDA ratio
    deaths_safe = df["deaths"].fillna(0).replace(0, 1)
    df["kda"] = (df["kills"].fillna(0) + df["assists"].fillna(0)) / deaths_safe

    # Numeric Level
    df["level"] = pd.to_numeric(df["level"], errors="coerce")

    # Normalize Role and Lane (handle N/A, NONE, empty strings)
    df["role"] = df["role"].astype(str).str.strip().str.upper()
    df["role"] = df["role"].replace(["N/A", "NONE", "NAN", ""], pd.NA)
    df["lane"] = df["lane"].astype(str).str.strip().str.upper()
    df["lane"] = df["lane"].replace(["N/A", "NONE", "NAN", ""], pd.NA)

    # Normalize Game Mode (preserve original case but normalize whitespace)
    df["game_mode"] = df["game_mode"].astype(str).str.strip()
    df["game_mode"] = df["game_mode"].replace(["N/A", "NONE", "NAN", ""], pd.NA)

    # Normalize Champion (preserve original case but normalize whitespace and handle N/A)
    df["champion"] = df["champion"].astype(str).str.strip()
    df["champion"] = df["champion"].replace(["N/A", "NONE", "NAN", ""], pd.NA)

    # Team lists
    df["blue_list"] = df["blue"].astype(str).apply(extract_names_from_blob)
    df["red_list"] = df["red"].astype(str).apply(extract_names_from_blob)

    # Hour-of-day
    df["hour"] = df["start"].dt.hour

    # Drop rows with missing critical fields
    df = df.dropna(subset=["start", "champion"])

    return df


# Converts victory-like values to 1 or 0
def normalize_victory(v) -> Optional[int]:
    if pd.isna(v):
        return pd.NA
    s = str(v).strip().lower()
    true_set = {"yes", "y", "true", "t", "1", "win", "won", "victory", "w"}
    false_set = {"no", "n", "false", "f", "0", "loss", "lost", "defeat", "l"}
    if s in true_set:
        return 1
    if s in false_set:
        return 0
    # Unknown token
    return pd.NA


# Parses a duration string like "24 minutes, 27 seconds" to minutes as float
def parse_duration_to_minutes(s: str) -> float:
    if not isinstance(s, str):
        return float("nan")
    mins = re.search(r"(\d+)\s*minute", s)
    secs = re.search(r"(\d+)\s*second", s)
    m = int(mins.group(1)) if mins else 0
    sec = int(secs.group(1)) if secs else 0
    return m + sec / 60.0


# Extracts summoner names wrapped in single quotes from a blob string
def extract_names_from_blob(s: str) -> List[str]:
    if not isinstance(s, str):
        return []
    return [m.strip() for m in re.findall(r"'([^']+)'", s)]


# Builds a normalized champion pick frequency distribution
def champion_distribution(df: pd.DataFrame) -> Dict[str, float]:
    cnt = Counter(df["champion"].astype(str).str.strip())
    total = sum(cnt.values())
    return {k: v / total for k, v in cnt.items()} if total > 0 else {}


# Builds a normalized 24-bin hour-of-day activity histogram
def hour_histogram(df: pd.DataFrame) -> List[float]:
    counts = [0] * 24
    for h in df["hour"].dropna().astype(int):
        if 0 <= h <= 23:
            counts[h] += 1
    total = sum(counts)
    return [c / total if total > 0 else 0.0 for c in counts]


# Builds a normalized frequency dictionary of all teammate names seen
def teammate_distribution(df: pd.DataFrame) -> Dict[str, float]:
    names = []
    if "blue_list" in df.columns:
        for lst in df["blue_list"]:
            names.extend(lst)
    if "red_list" in df.columns:
        for lst in df["red_list"]:
            names.extend(lst)
    cnt = Counter([n.strip() for n in names if n.strip()])
    total = sum(cnt.values())
    return {k: v / total for k, v in cnt.items()} if total > 0 else {}


# Builds a normalized role frequency distribution
def role_distribution(df: pd.DataFrame) -> Dict[str, float]:
    roles = df["role"].dropna().astype(str).str.strip()
    cnt = Counter(roles)
    total = sum(cnt.values())
    return {k: v / total for k, v in cnt.items()} if total > 0 else {}


# Builds a normalized lane frequency distribution
def lane_distribution(df: pd.DataFrame) -> Dict[str, float]:
    lanes = df["lane"].dropna().astype(str).str.strip()
    cnt = Counter(lanes)
    total = sum(cnt.values())
    return {k: v / total for k, v in cnt.items()} if total > 0 else {}


# Builds a normalized game mode frequency distribution
def game_mode_distribution(df: pd.DataFrame) -> Dict[str, float]:
    modes = df["game_mode"].dropna().astype(str).str.strip()
    cnt = Counter(modes)
    total = sum(cnt.values())
    return {k: v / total for k, v in cnt.items()} if total > 0 else {}


# Computes cosine similarity between two sparse distributions
def cosine_sim(a: Dict[str, float], b: Dict[str, float]) -> float:
    if not a or not b:
        return 0.0
    keys = set(a) | set(b)
    dot = sum(a.get(k, 0.0) * b.get(k, 0.0) for k in keys)
    na = math.sqrt(sum(v * v for v in a.values()))
    nb = math.sqrt(sum(v * v for v in b.values()))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


# Computes Jaccard similarity between two sets
def jaccard_sim(set_a: set, set_b: set) -> float:
    if not set_a and not set_b:
        return 0.0
    inter = len(set_a & set_b)
    union = len(set_a | set_b)
    return inter / union if union else 0.0


# Converts absolute difference to similarity on [0,1] using a scale
def scalar_similarity(a: float, b: float, scale: float) -> float:
    if any(pd.isna(x) for x in [a, b]):
        return 0.0
    diff = abs(float(a) - float(b))
    return max(0.0, 1.0 - min(1.0, diff / scale))


# Mode-specific duration thresholds (in minutes)
# These represent typical variation within each game mode
MODE_DURATION_THRESHOLDS = {
    "ARAM": 6.0,
    "Summoner's Rift": 10.0,
    "Arena": 6.0,
    "Ultra Rapid Fire": 6.0,
    "Ultimate Spellbook": 8.0,
    "One for All": 8.0,
    "Nexus Blitz": 6.0,
    "All Random Summoner's Rift": 8.0,
    "Tutorial": 5.0,
    "Dominion/Crystal Scar": 5.0,
    "Nexus Siege": 5.0,
    "Blood Hunt Assassin": 5.0,
    # Default threshold for unknown modes
    "default": 8.0,
}


# Computes duration similarity using mode-specific thresholds
def duration_similarity_by_mode(df1: pd.DataFrame, df2: pd.DataFrame) -> float:
    """
    Computes duration similarity by comparing durations within each game mode,
    using mode-specific thresholds. This accounts for the fact that different
    game modes have very different typical durations.
    Handles N/A/unknown modes as a special category.
    """
    # Normalize game modes: treat N/A, empty, etc. as "Unknown"
    def normalize_mode(mode):
        if pd.isna(mode):
            return "Unknown"
        mode_str = str(mode).strip()
        if mode_str.upper() in ("N/A", "NONE", "NAN", ""):
            return "Unknown"
        return mode_str

    # Get all game modes (including "Unknown" for N/A values)
    modes1 = set(normalize_mode(m) for m in df1["game_mode"])
    modes2 = set(normalize_mode(m) for m in df2["game_mode"])
    common_modes = modes1 & modes2

    if not common_modes:
        # No common modes - fall back to overall comparison with default threshold
        mean1 = df1["duration_min"].mean()
        mean2 = df2["duration_min"].mean()
        if any(pd.isna(x) for x in [mean1, mean2]):
            return 0.0
        threshold = MODE_DURATION_THRESHOLDS.get("default", 8.0)
        return scalar_similarity(mean1, mean2, threshold)

    # Calculate similarity for each common mode, weighted by frequency
    mode_similarities = []
    mode_weights = []

    for mode in common_modes:
        # Get matches for this mode in each dataframe
        df1_mode = df1[df1["game_mode"].apply(normalize_mode) == mode]
        df2_mode = df2[df2["game_mode"].apply(normalize_mode) == mode]

        # Skip if either dataframe has no valid duration data for this mode
        if len(df1_mode) == 0 or len(df2_mode) == 0:
            continue

        mean1 = df1_mode["duration_min"].mean()
        mean2 = df2_mode["duration_min"].mean()

        if any(pd.isna(x) for x in [mean1, mean2]):
            continue

        # Get mode-specific threshold (use default for "Unknown" modes)
        if mode == "Unknown":
            threshold = MODE_DURATION_THRESHOLDS.get("default", 8.0)
        else:
            threshold = MODE_DURATION_THRESHOLDS.get(mode, MODE_DURATION_THRESHOLDS["default"])

        # Calculate similarity for this mode
        mode_sim = scalar_similarity(mean1, mean2, threshold)

        # Weight by combined frequency (how often this mode appears in both files)
        weight = len(df1_mode) + len(df2_mode)

        mode_similarities.append(mode_sim)
        mode_weights.append(weight)

    if not mode_similarities:
        # No valid mode comparisons - fall back to overall
        mean1 = df1["duration_min"].mean()
        mean2 = df2["duration_min"].mean()
        if any(pd.isna(x) for x in [mean1, mean2]):
            return 0.0
        threshold = MODE_DURATION_THRESHOLDS.get("default", 8.0)
        return scalar_similarity(mean1, mean2, threshold)

    # Weighted average of mode-specific similarities
    total_weight = sum(mode_weights)
    if total_weight == 0:
        return 0.0

    weighted_sim = sum(sim * weight for sim, weight in zip(mode_similarities, mode_weights)) / total_weight
    return weighted_sim


# Heuristically guesses the focal player by most frequent name across matches
def guess_player_name(df: pd.DataFrame) -> Tuple[str, float]:
    freq = Counter()
    blues = df["blue_list"] if "blue_list" in df.columns else []
    reds = df["red_list"] if "red_list" in df.columns else []
    for blue, red in zip(blues, reds):
        for n in set(blue + red):
            freq[n] += 1
    if not freq:
        return "", 0.0
    name, count = freq.most_common(1)[0]
    conf = count / max(1, len(df))
    return name, conf


# Compares two match histories and return component similarities and an overall score
def compare_profiles(df1: pd.DataFrame, df2: pd.DataFrame) -> Dict[str, float]:

    # Feature 1: champion pool similarity (cosine on frequency)
    champ_sim = cosine_sim(champion_distribution(df1), champion_distribution(df2))

    # Feature 2: KDA profile similarity (mean and stdev)
    kda_mean_sim = scalar_similarity(df1["kda"].mean(), df2["kda"].mean(), scale=2.0)
    kda_std_sim = scalar_similarity(df1["kda"].std(ddof=0), df2["kda"].std(ddof=0), scale=1.0)
    kda_sim = 0.7 * kda_mean_sim + 0.3 * kda_std_sim

    # Feature 3: Winrate similarity
    wr1 = df1["victory"].mean() if len(df1) else pd.NA
    wr2 = df2["victory"].mean() if len(df2) else pd.NA
    winrate_sim = scalar_similarity(wr1, wr2, scale=0.25)

    # Feature 4: Average duration similarity (mode-aware)
    dur_sim = duration_similarity_by_mode(df1, df2)

    # Feature 5: Time-of-day habit similarity
    tod_sim = cosine_sim(
        {str(i): v for i, v in enumerate(hour_histogram(df1))},
        {str(i): v for i, v in enumerate(hour_histogram(df2))},
    )

    # Feature 6: Teammate overlap (names)
    team_sim = cosine_sim(teammate_distribution(df1), teammate_distribution(df2))

    # Feature 7: Role preference similarity
    role_sim = cosine_sim(role_distribution(df1), role_distribution(df2))

    # Feature 8: Lane preference similarity
    lane_sim = cosine_sim(lane_distribution(df1), lane_distribution(df2))

    # Feature 9: Average level similarity (indicates skill/playstyle)
    # Only compute if both files have sufficient level data (>50% valid)
    level_valid1 = df1["level"].notna().mean()
    level_valid2 = df2["level"].notna().mean()
    if level_valid1 >= 0.5 and level_valid2 >= 0.5:
        level_sim = scalar_similarity(df1["level"].mean(), df2["level"].mean(), scale=4.0)
    else:
        # If either file has sparse level data, set similarity to 0.5 (neutral)
        # to avoid penalizing accounts with missing level data
        level_sim = 0.5 if (level_valid1 < 0.5 or level_valid2 < 0.5) else 0.0

    # Feature 10: Game mode preference similarity
    # Lower weight since new modes are introduced periodically
    mode_sim = cosine_sim(game_mode_distribution(df1), game_mode_distribution(df2))

    # Weighted blend (adjusted weights to accommodate new features)
    # Game mode gets lower weight since new modes are introduced periodically
    weights = {
        "champ": 0.23,
        "kda": 0.16,
        "winrate": 0.09,
        "duration": 0.09,
        "time_of_day": 0.10,
        "teammates": 0.10,
        "role": 0.07,
        "lane": 0.07,
        "level": 0.04,
        "game_mode": 0.05,
    }
    overall = (
        weights["champ"] * champ_sim
        + weights["kda"] * kda_sim
        + weights["winrate"] * winrate_sim
        + weights["duration"] * dur_sim
        + weights["time_of_day"] * tod_sim
        + weights["teammates"] * team_sim
        + weights["role"] * role_sim
        + weights["lane"] * lane_sim
        + weights["level"] * level_sim
        + weights["game_mode"] * mode_sim
    )
    overall = min(1.0, max(0.0, overall))

    return {
        "champion_similarity": round(champ_sim, 4),
        "kda_similarity": round(kda_sim, 4),
        "winrate_similarity": round(winrate_sim, 4),
        "duration_similarity": round(dur_sim, 4),
        "time_of_day_similarity": round(tod_sim, 4),
        "teammate_overlap_similarity": round(team_sim, 4),
        "role_similarity": round(role_sim, 4),
        "lane_similarity": round(lane_sim, 4),
        "level_similarity": round(level_sim, 4),
        "game_mode_similarity": round(mode_sim, 4),
        "overall_score_0_100": round(overall * 100, 1),
        "guessed_player_file1": guess_player_name(df1)[0],
        "guess_conf_file1": round(guess_player_name(df1)[1], 3),
        "guessed_player_file2": guess_player_name(df2)[0],
        "guess_conf_file2": round(guess_player_name(df2)[1], 3),
    }


# Produces a short textual verdict from the overall score
def verdict(score_0_100: float) -> str:
    if score_0_100 >= 80:
        return "Very likely the same player"
    if score_0_100 >= 65:
        return "Likely the same player"
    if score_0_100 >= 50:
        return "Unclear"
    if score_0_100 >= 35:
        return "Likely different players"
    return "Very likely different players"


# Formats a similarity score as a percentage with visual bar
def format_similarity(score: float, width: int = 20) -> str:
    pct = score * 100
    filled = int(score * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"{pct:5.1f}% [{bar}]"


# Checks for temporal overlaps between matches from two dataframes
def find_temporal_overlaps(df1: pd.DataFrame, df2: pd.DataFrame, verbose: bool = True) -> List[Dict]:
    overlaps = []

    # Ensure we have start and stop columns
    if "start" not in df1.columns or "stop" not in df1.columns:
        return overlaps
    if "start" not in df2.columns or "stop" not in df2.columns:
        return overlaps

    if verbose:
        print("Analyzing temporal overlaps between matches...", end="", flush=True)
        total_comparisons = len(df1) * len(df2)
        print(f" ({len(df1)} × {len(df2)} = {total_comparisons:,} comparisons)")

    # Convert to timestamps for comparison
    df1_start = pd.to_datetime(df1["start"], errors="coerce")
    df1_stop = pd.to_datetime(df1["stop"], errors="coerce")
    df2_start = pd.to_datetime(df2["start"], errors="coerce")
    df2_stop = pd.to_datetime(df2["stop"], errors="coerce")

    # Check each match from df1 against each match from df2
    last_progress = 0
    for i1 in range(len(df1)):
        # Show progress every 10% or every 100 matches, whichever is more frequent
        if verbose and len(df1) > 10:
            progress = int((i1 / len(df1)) * 100)
            if progress >= last_progress + 10 or i1 % 100 == 0:
                print(f"  Progress: {progress}% ({i1}/{len(df1)} matches from file 1 checked)", end="\r", flush=True)
                last_progress = progress
        start1 = df1_start.iloc[i1]
        stop1 = df1_stop.iloc[i1]

        if pd.isna(start1) or pd.isna(stop1):
            continue

        row1 = df1.iloc[i1]

        for i2 in range(len(df2)):
            start2 = df2_start.iloc[i2]
            stop2 = df2_stop.iloc[i2]

            if pd.isna(start2) or pd.isna(stop2):
                continue

            row2 = df2.iloc[i2]

            # Check if time ranges overlap
            # Two ranges overlap if: start1 <= stop2 AND stop1 >= start2
            if start1 <= stop2 and stop1 >= start2:
                # Calculate overlap duration
                overlap_start = max(start1, start2)
                overlap_stop = min(stop1, stop2)
                overlap_duration = (overlap_stop - overlap_start).total_seconds() / 60.0  # in minutes

                # Get additional match info if available
                def safe_get(row, col, default="N/A"):
                    try:
                        val = row[col]
                        if pd.isna(val):
                            return default
                        val_str = str(val).strip()
                        # Also check for string "nan" (case-insensitive) as pandas sometimes converts NaN to string "nan"
                        if val_str.lower() in ("nan", "none", ""):
                            return default
                        return val_str
                    except (KeyError, IndexError):
                        return default

                champ1 = safe_get(row1, "champion")
                champ2 = safe_get(row2, "champion")
                mode1 = safe_get(row1, "game_mode")
                mode2 = safe_get(row2, "game_mode")

                overlaps.append({
                    "file1_index": i1,
                    "file1_start": start1,
                    "file1_stop": stop1,
                    "file1_champion": champ1,
                    "file1_mode": mode1,
                    "file2_index": i2,
                    "file2_start": start2,
                    "file2_stop": stop2,
                    "file2_champion": champ2,
                    "file2_mode": mode2,
                    "overlap_start": overlap_start,
                    "overlap_stop": overlap_stop,
                    "overlap_duration_minutes": overlap_duration,
                })

    if verbose:
        print(f"  Progress: 100% ({len(df1)}/{len(df1)} matches from file 1 checked)")
        if overlaps:
            print(f"  Found {len(overlaps)} overlapping match(es)")
        else:
            print("  No temporal overlaps found")

    return overlaps


# Prints human-readable comparison report
def print_readable_report(result: Dict, file1: str, file2: str, df1: pd.DataFrame = None, df2: pd.DataFrame = None, overlaps: List[Dict] = None, max_overlaps: int = None) -> None:
    print("=" * 80)
    print(" LoL Match History Comparison Report")
    print("=" * 80)
    print()

    # Summary section
    print("SUMMARY")
    print("-" * 80)
    print(f"Overall Similarity Score: {result['overall_score_0_100']:.1f}/100")
    print(f"Verdict: {result['verdict']}")
    print()

    # Player identification
    if result.get("guessed_player_file1") or result.get("guessed_player_file2"):
        print("IDENTIFIED PLAYERS")
        print("-" * 80)
        if result.get("guessed_player_file1"):
            conf1 = result.get("guess_conf_file1", 0) * 100
            print(f"File 1: {result['guessed_player_file1']} (confidence: {conf1:.1f}%)")
        if result.get("guessed_player_file2"):
            conf2 = result.get("guess_conf_file2", 0) * 100
            print(f"File 2: {result['guessed_player_file2']} (confidence: {conf2:.1f}%)")
        print()

    # Similarity metrics grouped by category
    print("SIMILARITY METRICS")
    print("-" * 80)

    # Gameplay metrics
    print("\nGameplay Performance:")
    print(f"  KDA Similarity:        {format_similarity(result['kda_similarity'])}")
    print(f"  Win Rate Similarity:   {format_similarity(result['winrate_similarity'])}")
    print(f"  Average Level:         {format_similarity(result['level_similarity'])}")

    # Champion & role preferences
    print("\nChampion & Role Preferences:")
    print(f"  Champion Pool:         {format_similarity(result['champion_similarity'])}")
    print(f"  Role Preference:       {format_similarity(result['role_similarity'])}")
    print(f"  Lane Preference:       {format_similarity(result['lane_similarity'])}")

    # Game settings
    print("\nGame Settings:")
    print(f"  Game Mode Preference:  {format_similarity(result['game_mode_similarity'])}")
    print(f"  Match Duration:        {format_similarity(result['duration_similarity'])}")

    # Social & timing
    print("\nSocial & Timing Patterns:")
    print(f"  Teammate Overlap:       {format_similarity(result['teammate_overlap_similarity'])}")
    print(f"  Time of Day Patterns:   {format_similarity(result['time_of_day_similarity'])}")


    # Temporal overlap check (only if overlaps were actually computed or skipped for a reason)
    if df1 is not None and df2 is not None:
        # Check if temporal overlap was skipped due to same player
        if result.get("temporal_overlap_skipped_reason") == "same_player_high_similarity":
            print("\n" + "=" * 80)
            print("TEMPORAL OVERLAP ANALYSIS")
            print("-" * 80)
            print("\nTemporal overlap analysis was skipped:")
            p1 = result.get("guessed_player_file1", "")
            overall_score = result.get("overall_score_0_100", 0)
            print(f"  Same player identified in both files ({p1}) with high confidence")
            print(f"  Overall similarity score is very high ({overall_score:.1f}/100)")
            print("  Temporal overlap analysis would not be meaningful (most matches would overlap)")
            print("\n" + "=" * 80)
        elif result.get("temporal_overlap_check_performed", False):
            print("\n" + "=" * 80)
            print("TEMPORAL OVERLAP ANALYSIS")
            print("-" * 80)

            # Use provided overlaps or check if we need to compute them
            if overlaps is None:
                overlaps = []

            if overlaps:
                print(f"\n⚠️  WARNING: Found {len(overlaps)} overlapping match(es)!")
                print("   This indicates the players were active at the same time,")
                print("   which strongly suggests they are DIFFERENT players.\n")

                # Limit displayed overlaps if max_overlaps is specified
                displayed_overlaps = overlaps
                if max_overlaps is None:
                    # User explicitly requested all overlaps
                    pass  # Show all
                elif len(overlaps) > max_overlaps:
                    # Limit to last N overlaps
                    displayed_overlaps = overlaps[-max_overlaps:]  # Show last N overlaps
                    print(f"Showing last {max_overlaps} of {len(overlaps)} overlapping matches:")
                    print("  (Use --max-overlaps to change this limit or --max-overlaps all to show all)\n")

                print("Overlapping Matches:")
                print()

                # Extract filenames and player names
                file1_name = os.path.basename(file1)
                file2_name = os.path.basename(file2)
                player1 = result.get("guessed_player_file1", "")
                player2 = result.get("guessed_player_file2", "")

                total_overlaps = len(overlaps)
                for i, overlap in enumerate(displayed_overlaps, 1):
                    overlap_num = total_overlaps - len(displayed_overlaps) + i
                    print(f"Overlap #{overlap_num}:")

                    # File 1 match with filename and player name
                    print(f"  File 1 ({file1_name}) Match:")
                    if player1:
                        print(f"    Player: {player1}")
                    print(f"    Start:  {overlap['file1_start'].strftime('%Y-%m-%d %H:%M:%S')}")
                    print(f"    Stop:   {overlap['file1_stop'].strftime('%Y-%m-%d %H:%M:%S')}")
                    print(f"    Champion: {overlap['file1_champion']}")
                    print(f"    Mode:     {overlap['file1_mode']}")

                    # File 2 match with filename and player name
                    print(f"  File 2 ({file2_name}) Match:")
                    if player2:
                        print(f"    Player: {player2}")
                    print(f"    Start:  {overlap['file2_start'].strftime('%Y-%m-%d %H:%M:%S')}")
                    print(f"    Stop:   {overlap['file2_stop'].strftime('%Y-%m-%d %H:%M:%S')}")
                    print(f"    Champion: {overlap['file2_champion']}")
                    print(f"    Mode:     {overlap['file2_mode']}")
                    print(f"  Overlap Duration: {overlap['overlap_duration_minutes']:.1f} minutes")
                    print(f"    ({overlap['overlap_start'].strftime('%Y-%m-%d %H:%M:%S')} - {overlap['overlap_stop'].strftime('%Y-%m-%d %H:%M:%S')})")
                    if i < len(displayed_overlaps):
                        print()

                print("\n" + "=" * 80)
                print("CONCLUSION: These are DIFFERENT players (temporal overlap detected)")
                print("=" * 80)
            else:
                print("\n✓ No temporal overlaps found.")
                print("  The match time ranges do not overlap, which is consistent")
                print("  with the possibility that these could be the same player.")
                print("\n" + "=" * 80)


def main():
    parser = argparse.ArgumentParser(
        description="Compare two LoL match CSVs and assess if the same person played"
    )
    parser.add_argument("file1", help="Path to first CSV")
    parser.add_argument("file2", help="Path to second CSV")
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Optionally limit number of matches from the top of each file",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print JSON output (default: human-readable format)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output in JSON format instead of human-readable format",
    )
    parser.add_argument(
        "--no-overlap-check",
        action="store_true",
        dest="skip_overlap",
        help="Skip temporal overlap analysis (faster, but less comprehensive)",
    )
    parser.add_argument(
        "--max-overlaps",
        type=str,
        default="20",
        help="Maximum number of temporal overlaps to display (default: 20, use 'all' to show all)",
    )
    args = parser.parse_args()

    print("Loading and parsing CSV files...")
    print(f"  Loading {args.file1}...", end="", flush=True)
    df1 = load_matches(args.file1)
    print(f" done ({len(df1)} matches)")
    print(f"  Loading {args.file2}...", end="", flush=True)
    df2 = load_matches(args.file2)
    print(f" done ({len(df2)} matches)")

    if args.limit and args.limit > 0:
        print(f"Limiting to {args.limit} matches per file...")
        df1 = df1.head(args.limit)
        df2 = df2.head(args.limit)

    print("\nAnalyzing match profiles and computing similarity metrics...")
    result = compare_profiles(df1, df2)
    result["verdict"] = verdict(result["overall_score_0_100"])
    print("  Analysis complete\n")

    # Check for temporal overlaps (unless disabled)
    overlaps = []
    if not args.skip_overlap:
        # Skip temporal overlap analysis if files are essentially the same
        # (same identified players with high confidence and very high overall similarity)
        p1 = result.get("guessed_player_file1", "")
        p2 = result.get("guessed_player_file2", "")
        conf1 = result.get("guess_conf_file1", 0)
        conf2 = result.get("guess_conf_file2", 0)
        overall_score = result.get("overall_score_0_100", 0)

        # Check if same player identified with high confidence and very high similarity
        same_player_high_confidence = (
            p1 and p2 and p1 == p2 and
            min(conf1, conf2) >= 0.3 and
            overall_score >= 80
        )

        if same_player_high_confidence:
            print("Skipping temporal overlap analysis:")
            print(f"  Same player identified in both files ({p1}) with high confidence")
            print(f"  Overall similarity score is very high ({overall_score:.1f}/100)")
            print("  Temporal overlap analysis would not be meaningful (most matches would overlap)\n")
            result["temporal_overlaps_count"] = 0
            result["has_temporal_overlap"] = False
            result["temporal_overlap_check_performed"] = False
            result["temporal_overlap_skipped_reason"] = "same_player_high_similarity"
        else:
            overlaps = find_temporal_overlaps(df1, df2, verbose=True)
            print()
            result["temporal_overlaps_count"] = len(overlaps)
            result["has_temporal_overlap"] = len(overlaps) > 0
            result["temporal_overlap_check_performed"] = True
    else:
        print("Skipping temporal overlap analysis (--no-overlap-check specified)\n")
        result["temporal_overlaps_count"] = 0
        result["has_temporal_overlap"] = False
        result["temporal_overlap_check_performed"] = False
    if overlaps:
        # Add overlap details to JSON output
        result["temporal_overlaps"] = [
            {
                "file1_index": o["file1_index"],
                "file1_start": o["file1_start"].isoformat(),
                "file1_stop": o["file1_stop"].isoformat(),
                "file1_champion": o["file1_champion"],
                "file1_mode": o["file1_mode"],
                "file2_index": o["file2_index"],
                "file2_start": o["file2_start"].isoformat(),
                "file2_stop": o["file2_stop"].isoformat(),
                "file2_champion": o["file2_champion"],
                "file2_mode": o["file2_mode"],
                "overlap_start": o["overlap_start"].isoformat(),
                "overlap_stop": o["overlap_stop"].isoformat(),
                "overlap_duration_minutes": round(o["overlap_duration_minutes"], 2),
            }
            for o in overlaps
        ]

    # Parse max_overlaps argument
    if args.max_overlaps.lower() == "all":
        max_overlaps = None  # None means show all
    else:
        try:
            max_overlaps = int(args.max_overlaps)
            if max_overlaps < 0:
                raise ValueError("max_overlaps must be non-negative")
        except ValueError:
            print(f"Error: --max-overlaps must be a non-negative integer or 'all', got '{args.max_overlaps}'")
            return 1

    # Output format selection
    if args.json:
        # JSON output (compact or pretty)
        if args.pretty:
            print(json.dumps(result, indent=2))
        else:
            print(json.dumps(result, separators=(",", ":")))
    else:
        # Human-readable format (default)
        print_readable_report(result, args.file1, args.file2, df1, df2, overlaps, max_overlaps)

        # If --pretty is also specified, also show JSON
        if args.pretty:
            print("\n" + "=" * 80)
            print("JSON Output (for programmatic use):")
            print("-" * 80)
            print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
